Add onCancelCallback, onFailureCallback in LLM Chat View
flutter/ai pull request #38
Opened 2024-12-25 22:13 UTC by ONLYstcm

- Added `onCancelCallback` to allow complete replacement of the default behavior of `AdaptiveSnackBar` when an `LlmCancelException` occurs. 
- Added `onFailureCallback` to enable overriding the default behavior of `AdaptiveAlertDialog` for `LlmFailureException` and general `LlmException`.
- Added `cancelMessage` to allow `CANCEL` message to be changed when an `LlmCancelException` occurs.
- Added `errorMessage` to allow `ERRORz message to be changed when an `LlmCancelException` occurs.

Implements: https://github.com/flutter/ai/issues/37

2024-12-26 20:38 UTC, csells commented
@ONLYstcm please include a new sample that shows off this capability.

2024-12-27 02:20 UTC, domesticmouse requested changes
@ONLYstcm Please sign the CLA. We can't merge the PR without it

2024-12-28 18:58 UTC, ONLYstcm commented
@csells @domesticmouse Please take a look now 🙏

2024-12-28 20:17 UTC, domesticmouse approved these changes
PTAL @csells

2025-01-27 01:20 UTC, csells commented
@ONLYstcm lgtm. only needs updates to the CHANGELOG.

2025-01-27 23:00 UTC, csells approved these changes
lgtm

2025-01-28 03:20 UTC, domesticmouse requested changes
Sorry to do this, but can we look at adding some test coverage here?

The upside of having test coverage is that we won't break this functionality with future changes as this functionality will be checked by our friend the GitHub CI bot.

Thanks!

2025-01-28 03:43 UTC, domesticmouse commented
Btw, update your PR to fix the `beta` CI issue. It was fixed in #51

2025-01-29 03:03 UTC, domesticmouse approved these changes

2025-01-29 03:03 UTC, domesticmouse commented
Landing as is

2025-01-29 03:03 UTC, merged